version: "3.9"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
  pgadmin:
    depends_on:
      - db
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  backend:
    depends_on:
      - db
    build: .
    environment:
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_NAME: my_db
      DATABASE_PORT: 5432
      WORKER_CLASS: uvicorn.workers.UvicornH11Worker
#      DATABASE_URL: postgresql://root:root@host.docker.internal:5432/my_db
#    command: uvicorn app.main:app --host 0.0.0.0
    command: python app/main.py
    volumes:
      - .:/app
    ports:
      - 8000:8000
    tty: true
